from enum import Enum


class DataType(str, Enum):
    NAME = "name"
    SURNAME = "surname"
    EMAIL = "email"
    PHONE = "phone"
    ADDRESS = "address"
    DNI = "dni"
    PASSPORT = "passport"
    CREDIT_CARD = "credit_card"
    IBAN = "iban"
    BANK_ACCOUNT = "bank_account"
    RUC = "ruc"
    RFC = "rfc"
    CURP = "curp"
    CPF = "cpf"
    SSN = "ssn"
    DATE_OF_BIRTH = "date_of_birth"
    GPS_COORDINATES = "gps_coordinates"
    IP_ADDRESS = "ip_address"
    URL = "url"
    TOKEN = "token"
    JWT = "jwt"
    API_KEY = "api_key"
    SECRET = "secret"
    MEDICAL_RECORD = "medical_record"
    BIOMETRIC = "biometric"
