apiVersion: v1
kind: Secret
metadata:
  name: enmask-secret
  namespace: enmask
  labels:
    app.kubernetes.io/name: enmask
type: Opaque
stringData:
  SECRET_KEY: "CHANGE_ME_IN_PRODUCTION"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "CHANGE_ME_IN_PRODUCTION"
  POSTGRES_META_DSN: "postgresql+asyncpg://postgres:CHANGE_ME_IN_PRODUCTION@postgres:5432/enmask_meta"
  MONGODB_META_URI: "mongodb://mongodb:27017"
  API_KEY: ""
  GOOGLE_CLIENT_ID: ""
